# Generated by Django 3.2.12 on 2023-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230721_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='prefer not to say', max_length=20, null=True),
        ),
    ]
